sudo: required
dist: focal
language: csharp
mono: none

services:
  - docker

before_install:
  - wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https
  - sudo apt-get update
  - sudo apt-get install -y dotnet-sdk-8.0

script:
  - docker-compose build

before_deploy:
  - echo "Logging in to Docker Hub"
  - echo "Haniel@123" | docker login --username "hanielsouza" --password-stdin
  - echo "Login Succeeded"

deploy:
  provider: script
  script:
    - docker images
    - echo "Tagging image..."
    - docker tag docker-to-aws-with-dotnet:latest hanielsouza/docker-to-aws-with-dotnet:latest
    - echo "Pushing image to Docker Hub..."
    - docker push hanielsouza/docker-to-aws-with-dotnet;
  on:
    branch: master

after_success:
  - sudo apt-get -y install python3-pip python3-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - pip3 uninstall -y wheel
  - pip3 install wheel
  - pip3 install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  - docker tag docker-to-aws-with-dotnet:latest hanielsouza/docker-to-aws-with-dotnet:latest
  - docker push hanielsouza/docker-to-aws-with-dotnet;

notifications:
  email: false
